# Generated by Django 6.1.1 on 2026-09-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(max_length=20)),
                ('establish_time', models.CharField(max_length=20)),
                ('mission', models.TextField(max_length=250)),
                ('about_image', models.ImageField(upload_to='uploads/%Y/%m/%d')),
                ('about_body', models.TextField(max_length=1000)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
    ]
